# Generated by Django 3.1.1 on 2020-09-23 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('store_name', models.CharField(max_length=50)),
                ('descriptiom', models.TextField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='store_image/')),
                ('fav', models.BooleanField(default=False)),
                ('create_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
