# Generated by Django 3.1.1 on 2020-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=50)),
                ('stnum', models.IntegerField()),
                ('teacher', models.CharField(choices=[('ali', 'ali'), ('sara', 'sara'), ('sima', 'sima')], max_length=50)),
            ],
        ),
    ]
